Repository milieuinfo/webcomponent-vl-ui-button, pull requests merged in 2019-09, with the labels that each got.

#27 UIG-218
  vl-button.src.js
Labels: maintenance

#28 Update link naar demo
  vl-button.src.js
Labels: maintenance

#29 Automatic commit via update script
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
  package-lock.json
  package.json
Labels: maintenance

#31 Update dependency @govflanders/vl-ui-core to v3.9.0
  package-lock.json
  package.json
Labels: dependencies

#30 Update dependency @govflanders/vl-ui-button to v3.9.0
  package-lock.json
  package.json
Labels: dependencies

#40 Update dependency vl-ui-pill to v1.0.6
  package-lock.json
  package.json
Labels: dependencies

#39 Update dependency vl-ui-link to v1.1.9
  package-lock.json
  package.json
Labels: dependencies

#38 Update dependency vl-ui-icon to v2.0.11
  package-lock.json
  package.json
Labels: dependencies

#37 Update dependency vl-ui-core to v1.4.6
  package-lock.json
  package.json
Labels: dependencies

#36 Update dependency replace to v1.1.1
  package-lock.json
  package.json
Labels: dependencies

#35 Update dependency @govflanders/vl-ui-util to v3.9.0
  package-lock.json
  package.json
Labels: dependencies

#34 Update dependency @govflanders/vl-ui-pill to v3.9.0
  package-lock.json
  package.json
Labels: dependencies

#33 Update dependency @govflanders/vl-ui-link to v3.9.0
  package-lock.json
  package.json
Labels: dependencies

#32 Update dependency @govflanders/vl-ui-icon to v3.9.0
  package-lock.json
  package.json
Labels: dependencies

#10 Update dependency np to v3.1.0
  package-lock.json
  package.json
Labels: renovate

#47 Automatic commit via update script
  demo/demo.css
  demo/demo.css.map
  package-lock.json
  style.css
  style.css.map
Labels: maintenance

#49 Update and install latest util
  .github/ISSUE_TEMPLATE/task.md
  bamboo-specs/bamboo.yml
  demo/demo.css
  demo/demo.css.map
  package-lock.json
  package.json
  style.css
  style.css.map
Labels: maintenance

#54 Update vl-ui-util
  CODEOWNERS
  demo/demo.css
  demo/demo.css.map
  package-lock.json
  package.json
  style.css
  style.css.map
Labels: maintenance
