Repository milieuinfo/webcomponent-vl-ui-button, pull requests merged in 2020-01, with the labels that each got.

#76 package-lock
  demo/demo.css
  demo/demo.css.map
  package-lock.json
  package.json
  style.css
  style.css.map
  vl-button.js
Labels: chore

#77 Update package-lock
  package-lock.json
Labels: chore

#80 Update vl-ui-util
  package-lock.json
  package.json
Labels: maintenance

#83 #81: Fix cyclic dependency (#82)
  package-lock.json
  style.css
  style.css.map
  vl-button.js
Labels: chore

#84 Fix demo-pagina
  demo/vl-button.html
  package-lock.json
  package.json
  test/e2e/button.test.js
  test/e2e/pages/vl-button.page.js
Labels: bugfix

#85 Er word te snel gekeken of de tekst in de button al veranderd is
  test/e2e/button.test.js
  test/e2e/pages/vl-button.page.js
Labels: bugfix

#86 Voeg callback toe aan after en before
  test/e2e/button.test.js
Labels: bugfix

#88 Update vl-ui-util docker containers
  bamboo-specs/bamboo.yml
  demo/demo.css
  demo/demo.css.map
  package-lock.json
  package.json
  style.css
  style.css.map
  test/docker-compose.yml
Labels: bugfix

#89 Nieuwe versie util
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
Labels: bugfix

#91 Verwijder pretest fase (installeren chromedriver). Deze komt via vl-ui-util binnen
  package.json
Labels: bugfix

#87 Overbodig NPM release import scripts verwijderd
  package.json
  vl-button.js
Labels: maintenance

#92 Node max session
  bamboo-specs/bamboo.yml
  demo/demo.css
  demo/demo.css.map
  package-lock.json
  package.json
  style.css
  style.css.map
  test/docker-compose.yml
Labels: bugfix

#93 Node max session
  package-lock.json
  package.json
Labels: bugfix

#94 Update vl-ui-util
  demo/demo.css
  demo/demo.css.map
  package-lock.json
  style.css
  style.css.map
Labels: maintenance
